apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
data:
  POSTGRES_DB: "url_shortener"
  POSTGRES_USER: "postgres"
  POSTGRES_PORT: "5432"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/url_shortener"
  SPRING_DATASOURCE_USERNAME: "postgres"